{
    "openapi": "3.0.0",
    "info": {
        "title": "Pomelo Travel Company APIs",
        "version": "1.0"
    },
    "paths": {
        "/api/companydata": {
            "post": {
                "operationId": "getcompanydata",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "company_id": "1"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
        "/api/login": {
            "post": {
                "operationId": "login2",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    
                                },
                                "type": "object",
                                "example": {
                                    "email": "test@test.com",
                                    "password": "123456",
                                    "company_id": "1"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
        "/api/register": {
            "post": {
                "operationId": "register2",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "first_name": {
                                        "type": "string"
                                    },
                                    "last_name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "company_id": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "first_name": "Jhon",
                                    "last_name": "tom",
                                    "email": "test@test.com",
                                    "password": "123456",
                                    "company_id": "1"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
        "/api/admin/users/login": {
            "post": {
                "operationId": "admin_login",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "test@test.com",
                                    "password": "123456"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
        
		"/api/admin/company/addnew": {
            "post": {
                "operationId": "admin_add_new_company",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "contact_number": {
                                        "type": "string"
                                    },
                                    "website_url": {
                                        "type": "string"
                                    },
                                    "address": {
                                        "type": "string"
                                    },
                                    "owner_name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "company_logo": {
                                        "type": "string"
                                    },
                                    "app_url": {
                                        "type": "string"
                                    },
                                    "live_agent_url": {
                                        "type": "string"
                                    },
                                    "stripe_publishable_key": {
                                        "type": "string"
                                    },
                                    "stripe_secret_key": {
                                        "type": "string"
                                    },
                                    "prefix": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "test@test.com",
                                    "contact_number": "123456",
                                    "website_url": "123456",
                                    "address": "123456",
                                    "owner_name": "123456",
                                    "email": "123456",
                                    "company_logo": "123456",
                                    "app_url": "123456",
                                    "live_agent_url": "123456",
                                    "stripe_publishable_key": "123456",
                                    "stripe_secret_key": "123456",
                                    "prefix": "123456"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
	
		"/api/admin/company/editcompany": {
            "post": {
                "operationId": "admin_add_new_company2",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
								"company_id": {
                                        "type": "integer"
                                    },
                                    "name": {
                                        "type": "string"
                                    },
                                    "contact_number": {
                                        "type": "string"
                                    },
                                    "website_url": {
                                        "type": "string"
                                    },
                                    "address": {
                                        "type": "string"
                                    },
                                    "owner_name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "company_logo": {
                                        "type": "string"
                                    },
                                    "app_url": {
                                        "type": "string"
                                    },
                                    "live_agent_url": {
                                        "type": "string"
                                    },
                                    "stripe_publishable_key": {
                                        "type": "string"
                                    },
                                    "stripe_secret_key": {
                                        "type": "string"
                                    },
                                    "prefix": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
									"company_id": "3",
                                    "name": "test@test.com",
                                    "contact_number": "123456",
                                    "website_url": "123456",
                                    "address": "123456",
                                    "owner_name": "123456",
                                    "email": "123456",
                                    "company_logo": "123456",
                                    "app_url": "123456",
                                    "live_agent_url": "123456",
                                    "stripe_publishable_key": "123456",
                                    "stripe_secret_key": "123456",
                                    "prefix": "123456"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
		
		"/api/admin/company/view": {
            "post": {
                "operationId": "admin_view_company",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "id": "5"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
		
		"/api/admin/company/companylist": {
            "post": {
                "operationId": "admin_list_company",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
		
		"/api/admin/users/manage": {
            "post": {
                "operationId": "admin_manage_users",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

		"/api/admin/users/addnew": {
            "post": {
                "operationId": "admin_addnew_users",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    
                                },
                                "type": "object",
                                "example": {
									"email":"raj@testing.com",
									"password":"123456",
									"company_id":"1",
									"user_type_id":"0",
									"first_name":"",
									"last_name":""
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
		
		"/api/admin/users/edit": {
            "post": {
                "operationId": "admin_edit_users",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "email":"raj@testing.com",
                                    "password":"123456",
                                    "company_id":"1",
                                    "user_type_id":"0",
                                    "first_name":"",
                                    "last_name":"",
                                    "id": "1"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
		
		"/api/admin/users/viewdetails": {
            "post": {
                "operationId": "admin_viewdetails",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "id": "19"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
		
		"/api/admin/users/deleteusertype": {
            "post": {
                "operationId": "admin_deleteusertype",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "user_type_id": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
		
		"/api/admin/users/newusertype": {
            "post": {
                "operationId": "admin_newusertype",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "company_id": 1,
                                    "name": "admin"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
		
		"/api/admin/users/editusertype": {
            "post": {
                "operationId": "admin_editusertype",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "company_id": 1,
                                    "name": "admin",
                                    "user_type_id":2
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
		
		"/api/admin/users/viewusertype": {
            "post": {
                "operationId": "admin_viewusertype",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "user_type_id": 7
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

        "/api/admin/company/changestatus": {
            "post": {
                "operationId": "admin_changestatus",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "company_id": 1,
                                    "status": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

        "/api/admin/company/deletecompany": {
            "post": {
                "operationId": "admin_deletecompany",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "company_id": 7
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

        "/api/admin/users/deleteuser": {
            "post": {
                "operationId": "admin_deleteuser2",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "user_id": 7
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

        "/api/admin/users/changepass": {
            "post": {
                "operationId": "admin_changepass",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "new_pass":"12345678",
                                    "confirm_pass":"12345678",
                                    "old_pass":"1111"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

        "/api/admin/users/updateprofile": {
            "post": {
                "operationId": "admin_updateprofile",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "name":"Super Admin",
                                    "email":"admin@mail.com"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

        "/api/admin/packages/manage": {
            "post": {
                "operationId": "admin_pack_manage",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {

                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

        "/api/admin/packages/addnew": {
            "post": {
                "operationId": "admin_pack_addnew",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "subscription_type":"year",
                                    "subscription_name":"Sliver",
                                    "description":"any extra feature",
                                    "status":0,
                                    "price":12
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

        "/api/admin/packages/edit": {
            "post": {
                "operationId": "admin_pack_edit",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "subscription_type":"year",
                                    "subscription_name":"Sliver",
                                    "description":"any extra feature",
                                    "status":0,
                                    "price":12,
                                    "id": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

        "/api/admin/packages/viewdetails": {
            "post": {
                "operationId": "admin_pack_viewdetails",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "id": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

        "/api/admin/packages/deletepackage": {
            "post": {
                "operationId": "admin_deletepackage",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "id": 7
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },

        "/api/admin/packages/changestatus": {
            "post": {
                "operationId": "admin_pack_changestatus",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "id": 7,
                                    "status": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com"
                    }
                ]
            }
        },
        "/api/deals": {
            "post": {
                "operationId": "Create_Deal",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "title": "Summer deal",
                                    "price": "40",
                                    "company": "1",
                                    "ticket_type": "Basic Economy",
                                    "source": "2",
                                    "destination": "7",
                                    "duration_from": "2020-07-24",
                                    "duration_to": "2020-08-24",
                                    "deals_airlines[0][airline]": "1",
                                    "deals_airlines[1][airline]": "2",
                                    "user_type": "Paid",
                                    "type": "Domestic",
                                    "booking_links": "https://www.google.com/, yahoo.com",
                                    "departure_airports[0][airport]": "11",
                                    "departure_airports[0][price]": "38",
                                    "departure_airports[1][airport]": "31",
                                    "departure_airports[1][price]": "35",
                                    "featured_image": "/C:/Users/HP/Downloads/the-test-fun-for-friends-screenshot.png"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },
        "/api/deals/2": {
            "get": {
                "operationId": "micro_deal_view",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {

                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },
        "/api/deals/1": {
            "put": {
                "operationId": "micri_putupdate",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "title": "Test Deal",
                                    "price": "4000",
                                    "code": "BZRR1234",
                                    "company": "1",
                                    "ticket_type": "economy",
                                    "source": "2",
                                    "destination": "7",
                                    "duration": "MARCH-APRIL",
                                    "airlines": "INDIGO",
                                    "type": "DOMESTIC",
                                    "booking_links": "https://www.googles.com/"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },
        "/api/deals/5": {
            "delete": {
                "operationId": "micro_delete",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {

                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },
        "/api/deals/search": {
            "post": {
                "operationId": "micro_searchbytitle",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "title": "Deal Test"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },



        "/api/airports": {
            "post": {
                "operationId": "micro_create_airport",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "country": "ddd",
                                    "city": "4000",
                                    "name": "BZRR1234",
                                    "IATA": "1",
                                    "ticket_type": "economy",
                                    "longitude": "2",
                                    "latitude": "7",
                                    "type": "MARCH-APRIL",
                                    "time_zone": "INDIGO"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },

        "/api/airports/1": {
            "delete": {
                "operationId": "micro_airport_delete",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {

                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },

        "/api/airports/5": {
            "get": {
                "operationId": "micro_airport_getairport",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {

                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },

        "/api/airports/companywise/2": {
            "get": {
                "operationId": "micrip_companywise",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {

                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },

        "/api/airports/domestic/1": {
            "get": {
                "operationId": "micro_domestic",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {

                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },

        "/api/airports/search": {
            "post": {
                "operationId": "micro_search_airports",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "name": "Mumbai airport"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },

        "/api/airlines": {
            "get": {
                "operationId": "micro_airlines2",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {

                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },

        "/api/airlines/1": {
            "get": {
                "operationId": "micro_airlines_by_id",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {

                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },



        "/api/airlines/125": {
            "put": {
                "operationId": "updateairlenis",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "name": "HHHH"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },

        "/api/airlines/126": {
            "delete": {
                "operationId": "delete_airlines",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {

                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },

        "/api/airlines/search": {
            "post": {
                "operationId": "seach_airlines_by_title",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "name": "Air Canada"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        },

        "/oauth/token": {
            "post": {
                "operationId": "token_auth_login",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {

                                },
                                "type": "object",
                                "example": {
                                    "username": "asd@asd.com",
                                    "password": "asws55",
                                    "grant_type": "pass",
                                    "client_id": "8",
                                    "client_secret": "pATJeDNqG9ddddUJ45fg545er9Gr2Qu3lXxCaWC0UGS"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "servers": [
                    {
                        "url": "https://api.pomelodev.com/deals"
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "name": "bearerAuth",
                "bearerFormat": "JWT",
                "scheme": "bearer"
            }
        }
    }
}